### PR TITLE
Dev/emergencial/2.4.3.12

### PR DESCRIPTION
**Pull request by OnlyLightMatters**
For parts which are new from 1.7 or which have been revamped with a new partname.

### CODE REVIEW

**Comment by OnlyLightMatters** [comment]
Is this this way you want things to be merged in TS ?

**Comment by Lisias** [comment]
Hi. Sorry being late, I got slightly sick in the past days, getting better today.

This is near enough the way I like things, I will change myself when needed ("moistly" :P remarks about when the part came to life - 1.8.1, 1.9.0, etc)

**Comment by Lisias** [comment]
(I will port this also to the DEV branch - it is wha will be, someday, the 2.5 release when things will be back to "normal" around here!)

**Comment by Lisias** [comment]
For the records, https://github.com/net-lisias-ksp/TweakScale/issues/101

**Pull request merged**
