### PR TITLE
Remove files blocking remote cloning.

### PR DESCRIPTION
**Pull request by 7ranceaddic7**
These files cause errors that bork remote cloning. Probably has something to do with being Safari. 
error: invalid path '... Kerbal Sp.01.pdf'
error: invalid path '... Kerbal Sp.01.webarchive'
error: invalid path '... Kerbal Sp.67.pdf'
error: invalid path '... Kerbal Sp.67.webarchive'

Alternative coming.

### CODE REVIEW

**Comment by Lisias** [comment]
These files are my legal safety belts. They are legal evidences of the chain of "ownership" and licensing terms. They need to be on the repository in the event the source page vanishes.

From where you are trying to clone this? People are cloning this on github, and I just cloned it from my bitbucket account without problems...

**Comment by 7ranceaddic7** [comment]
I can clone fine in GitHub.  I can't download to LOCAL.

Also, the URL shortcut is a COMPETE archival record (every page) of the entire thread.  I just thought that would be a better option than just the first and last.

It's your repository.  I'm just a lurker. What you say goes.

**Comment by Lisias** [comment]
Humm let me check that, it should be only the first page of the thread, where the legal information I need is...

**Comment by Lisias** [comment]
AH, I found evidences of the licensing terms of some artefacts that were incorporated into TweakScale before my time, so I dumped that pages too.

I don't have an explanation for you being unable to clone this on your machine. I have no notice of someone with this problem before...

**Comment by 7ranceaddic7** [comment]
Clone the project from VS to another location.  See what happens.

**Comment by Lisias** [comment]
> Clone the project from VS to another location. See what happens.

Ah, so is that... I don't use VS for this, I use SourceTree. The git support on IDEs are punny - and I'm not talking VS, I'm talking IDE - from Eclipse and Netbeans to Visual Studio'98 and now current VS, the support for Code Management Systems is less than minimal, it's minimalistic and "emasculating".

So I just gave up on them decades ago. I prefer to use git-gui on Quartz to waste my time using the embedded GIT support on VS. :D 

And about the big files, besides annoying in your case, they really need to be there. It will avoid copyright trolling not only to me, but also to everybody that clones this repo in the years to come. Copyright Laws are insane, and became yet more insane nowadays (and stunts like CC are throwing gas on fire).

(and, yeah, I got hit more than once - believe me, it's safer this way).

I will see if there's something on VS that can be configured to allow you to clone this on it.

**Comment by Lisias** [comment]
What's your VS by the way?

**Comment by Lisias** [comment]
besides inconvenient, local laws recommends that copyright evidences should be tracked in a place where I have control.

The commits are signed with my key, and I don't risk a technical problem or even a GDPR take down ending up with evidences vanishing in the thin air.

And the[ open hostility](https://web.archive.org/web/20190305213208/https://forum.kerbalspaceprogram.com/index.php?/topic/173105-reusing-squads-resources-for-new-mods-are-allowed/) I had to withhold in the past suggests I should be careful.

So I'm closing this.

**Comment by 7ranceaddic7** [comment]
Don't know how I missed this, but just as an FY,I VS2019.

**Pull request closed without merging**
